// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 12. 3. 오후 2:45:29
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["F:/frontend/youtube/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/frontend/youtube/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/frontend/youtube/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/frontend/youtube/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/frontend/youtube/frontend/plugins/**/*.{js,ts,mjs}","F:/frontend/youtube/frontend/composables/**/*.{js,ts,mjs}","F:/frontend/youtube/frontend/utils/**/*.{js,ts,mjs}","F:/frontend/youtube/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/frontend/youtube/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/frontend/youtube/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/frontend/youtube/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;